var modules =
[
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", "group___c_m_s_i_s___core___instruction_interface" ],
    [ "CMSIS SIMD Intrinsics", "group___c_m_s_i_s___s_i_m_d__intrinsics.html", null ],
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "group___c_m_s_i_s___core___function_interface.html", "group___c_m_s_i_s___core___function_interface" ],
    [ "HAL CRYP Aliased Defines maintained for legacy purpose", "group___h_a_l___a_e_s___aliased___defines.html", null ],
    [ "HAL ADC Aliased Defines maintained for legacy purpose", "group___h_a_l___a_d_c___aliased___defines.html", null ],
    [ "HAL CEC Aliased Defines maintained for legacy purpose", "group___h_a_l___c_e_c___aliased___defines.html", null ],
    [ "HAL COMP Aliased Defines maintained for legacy purpose", "group___h_a_l___c_o_m_p___aliased___defines.html", null ],
    [ "HAL CORTEX Aliased Defines maintained for legacy purpose", "group___h_a_l___c_o_r_t_e_x___aliased___defines.html", null ],
    [ "HAL CRC Aliased Defines maintained for legacy purpose", "group___h_a_l___c_r_c___aliased___defines.html", null ],
    [ "HAL DAC Aliased Defines maintained for legacy purpose", "group___h_a_l___d_a_c___aliased___defines.html", null ],
    [ "HAL DMA Aliased Defines maintained for legacy purpose", "group___h_a_l___d_m_a___aliased___defines.html", null ],
    [ "HAL FLASH Aliased Defines maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___defines.html", null ],
    [ "HAL JPEG Aliased Macros maintained for legacy purpose", "group___h_a_l___j_p_e_g___aliased___macros.html", null ],
    [ "HAL SYSCFG Aliased Defines maintained for legacy purpose", "group___h_a_l___s_y_s_c_f_g___aliased___defines.html", null ],
    [ "LL FMC Aliased Defines maintained for compatibility purpose", "group___l_l___f_m_c___aliased___defines.html", null ],
    [ "LL FSMC Aliased Defines maintained for legacy purpose", "group___l_l___f_s_m_c___aliased___defines.html", null ],
    [ "HAL GPIO Aliased Macros maintained for legacy purpose", "group___h_a_l___g_p_i_o___aliased___macros.html", null ],
    [ "HAL HRTIM Aliased Macros maintained for legacy purpose", "group___h_a_l___h_r_t_i_m___aliased___macros.html", null ],
    [ "HAL I2C Aliased Defines maintained for legacy purpose", "group___h_a_l___i2_c___aliased___defines.html", null ],
    [ "HAL IRDA Aliased Defines maintained for legacy purpose", "group___h_a_l___i_r_d_a___aliased___defines.html", null ],
    [ "HAL IWDG Aliased Defines maintained for legacy purpose", "group___h_a_l___i_w_d_g___aliased___defines.html", null ],
    [ "HAL LPTIM Aliased Defines maintained for legacy purpose", "group___h_a_l___l_p_t_i_m___aliased___defines.html", null ],
    [ "HAL NAND Aliased Defines maintained for legacy purpose", "group___h_a_l___n_a_n_d___aliased___defines.html", null ],
    [ "HAL NOR Aliased Defines maintained for legacy purpose", "group___h_a_l___n_o_r___aliased___defines.html", null ],
    [ "HAL OPAMP Aliased Defines maintained for legacy purpose", "group___h_a_l___o_p_a_m_p___aliased___defines.html", null ],
    [ "HAL I2S Aliased Defines maintained for legacy purpose", "group___h_a_l___i2_s___aliased___defines.html", null ],
    [ "HAL PCCARD Aliased Defines maintained for legacy purpose", "group___h_a_l___p_c_c_a_r_d___aliased___defines.html", null ],
    [ "HAL RTC Aliased Defines maintained for legacy purpose", "group___h_a_l___r_t_c___aliased___defines.html", null ],
    [ "HAL SMARTCARD Aliased Defines maintained for legacy purpose", "group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___defines.html", null ],
    [ "HAL SMBUS Aliased Defines maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___defines.html", null ],
    [ "HAL SPI Aliased Defines maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___defines.html", null ],
    [ "HAL TIM Aliased Defines maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___defines.html", null ],
    [ "HAL TSC Aliased Defines maintained for legacy purpose", "group___h_a_l___t_s_c___aliased___defines.html", null ],
    [ "HAL UART Aliased Defines maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___defines.html", null ],
    [ "HAL USART Aliased Defines maintained for legacy purpose", "group___h_a_l___u_s_a_r_t___aliased___defines.html", null ],
    [ "HAL WWDG Aliased Defines maintained for legacy purpose", "group___h_a_l___w_w_d_g___aliased___defines.html", null ],
    [ "HAL CAN Aliased Defines maintained for legacy purpose", "group___h_a_l___c_a_n___aliased___defines.html", null ],
    [ "HAL ETH Aliased Defines maintained for legacy purpose", "group___h_a_l___e_t_h___aliased___defines.html", null ],
    [ "HAL DCMI Aliased Defines maintained for legacy purpose", "group___h_a_l___d_c_m_i___aliased___defines.html", null ],
    [ "HAL PPP Aliased Defines maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___defines.html", null ],
    [ "HAL CRYP Aliased Functions maintained for legacy purpose", "group___h_a_l___c_r_y_p___aliased___functions.html", null ],
    [ "HAL HASH Aliased Functions maintained for legacy purpose", "group___h_a_l___h_a_s_h___aliased___functions.html", null ],
    [ "HAL Generic Aliased Functions maintained for legacy purpose", "group___h_a_l___aliased___functions.html", null ],
    [ "HAL FLASH Aliased Functions maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___functions.html", null ],
    [ "HAL I2C Aliased Functions maintained for legacy purpose", "group___h_a_l___i2_c___aliased___functions.html", null ],
    [ "HAL PWR Aliased maintained for legacy purpose", "group___h_a_l___p_w_r___aliased.html", null ],
    [ "HAL SMBUS Aliased Functions maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___functions.html", null ],
    [ "HAL SPI Aliased Functions maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___functions.html", null ],
    [ "HAL TIM Aliased Functions maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___functions.html", null ],
    [ "HAL UART Aliased Functions maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___functions.html", null ],
    [ "HAL LTDC Aliased Functions maintained for legacy purpose", "group___h_a_l___l_t_d_c___aliased___functions.html", null ],
    [ "HAL PPP Aliased Functions maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___functions.html", null ],
    [ "HAL CRYP Aliased Macros maintained for legacy purpose", "group___h_a_l___a_e_s___aliased___macros.html", null ],
    [ "HAL Generic Aliased Macros maintained for legacy purpose", "group___h_a_l___aliased___macros.html", null ],
    [ "HAL ADC Aliased Macros maintained for legacy purpose", "group___h_a_l___a_d_c___aliased___macros.html", null ],
    [ "HAL DAC Aliased Macros maintained for legacy purpose", "group___h_a_l___d_a_c___aliased___macros.html", null ],
    [ "HAL DBGMCU Aliased Macros maintained for legacy purpose", "group___h_a_l___d_b_g_m_c_u___aliased___macros.html", null ],
    [ "HAL COMP Aliased Macros maintained for legacy purpose", "group___h_a_l___c_o_m_p___aliased___macros.html", null ],
    [ "HAL FLASH Aliased Macros maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___macros.html", null ],
    [ "HAL I2C Aliased Macros maintained for legacy purpose", "group___h_a_l___i2_c___aliased___macros.html", null ],
    [ "HAL I2S Aliased Macros maintained for legacy purpose", "group___h_a_l___i2_s___aliased___macros.html", null ],
    [ "HAL IRDA Aliased Macros maintained for legacy purpose", "group___h_a_l___i_r_d_a___aliased___macros.html", null ],
    [ "HAL IWDG Aliased Macros maintained for legacy purpose", "group___h_a_l___i_w_d_g___aliased___macros.html", null ],
    [ "HAL LPTIM Aliased Macros maintained for legacy purpose", "group___h_a_l___l_p_t_i_m___aliased___macros.html", null ],
    [ "HAL OPAMP Aliased Macros maintained for legacy purpose", "group___h_a_l___o_p_a_m_p___aliased___macros.html", null ],
    [ "HAL PWR Aliased Macros maintained for legacy purpose", "group___h_a_l___p_w_r___aliased___macros.html", null ],
    [ "HAL RCC Aliased maintained for legacy purpose", "group___h_a_l___r_c_c___aliased.html", null ],
    [ "HAL RNG Aliased Macros maintained for legacy purpose", "group___h_a_l___r_n_g___aliased___macros.html", null ],
    [ "HAL RTC Aliased Macros maintained for legacy purpose", "group___h_a_l___r_t_c___aliased___macros.html", null ],
    [ "HAL SD Aliased Macros maintained for legacy purpose", "group___h_a_l___s_d___aliased___macros.html", null ],
    [ "HAL SMARTCARD Aliased Macros maintained for legacy purpose", "group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___macros.html", null ],
    [ "HAL SMBUS Aliased Macros maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___macros.html", null ],
    [ "HAL SPI Aliased Macros maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___macros.html", null ],
    [ "HAL UART Aliased Macros maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___macros.html", null ],
    [ "HAL USART Aliased Macros maintained for legacy purpose", "group___h_a_l___u_s_a_r_t___aliased___macros.html", null ],
    [ "HAL USB Aliased Macros maintained for legacy purpose", "group___h_a_l___u_s_b___aliased___macros.html", null ],
    [ "HAL TIM Aliased Macros maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___macros.html", null ],
    [ "HAL ETH Aliased Macros maintained for legacy purpose", "group___h_a_l___e_t_h___aliased___macros.html", null ],
    [ "HAL LTDC Aliased Macros maintained for legacy purpose", "group___h_a_l___l_t_d_c___aliased___macros.html", null ],
    [ "HAL SAI Aliased Macros maintained for legacy purpose", "group___h_a_l___s_a_i___aliased___macros.html", null ],
    [ "HAL SPDIFRX Aliased Macros maintained for legacy purpose", "group___h_a_l___s_p_d_i_f_r_x___aliased___macros.html", null ],
    [ "HAL HRTIM Aliased Functions maintained for legacy purpose", "group___h_a_l___h_r_t_i_m___aliased___functions.html", null ],
    [ "HAL QSPI Aliased Macros maintained for legacy purpose", "group___h_a_l___q_s_p_i___aliased___macros.html", null ],
    [ "HAL PPP Aliased Macros maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___macros.html", null ],
    [ "xCoRoutineCreate", "group__x_co_routine_create.html", null ],
    [ "vCoRoutineSchedule", "group__v_co_routine_schedule.html", null ],
    [ "crSTART", "group__cr_s_t_a_r_t.html", null ],
    [ "crDELAY", "group__cr_d_e_l_a_y.html", null ],
    [ "crQUEUE_SEND", "group__cr_q_u_e_u_e___s_e_n_d.html", null ],
    [ "crQUEUE_RECEIVE", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html", null ],
    [ "crQUEUE_SEND_FROM_ISR", "group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html", null ],
    [ "crQUEUE_RECEIVE_FROM_ISR", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html", null ],
    [ "EventGroup", "group___event_group.html", "group___event_group" ],
    [ "xMessageBufferCreate", "group__x_message_buffer_create.html", null ],
    [ "xMessageBufferCreateStatic", "group__x_message_buffer_create_static.html", null ],
    [ "xMessageBufferSend", "group__x_message_buffer_send.html", null ],
    [ "xMessageBufferSendFromISR", "group__x_message_buffer_send_from_i_s_r.html", null ],
    [ "xMessageBufferReceive", "group__x_message_buffer_receive.html", null ],
    [ "xMessageBufferReceiveFromISR", "group__x_message_buffer_receive_from_i_s_r.html", null ],
    [ "xMessageBufferReset", "group__x_message_buffer_reset.html", null ],
    [ "xMessageBufferSpaceAvailable", "group__x_message_buffer_space_available.html", null ],
    [ "xMessageBufferNextLengthBytes", "group__x_message_buffer_next_length_bytes.html", null ],
    [ "xMessageBufferSendCompletedFromISR", "group__x_message_buffer_send_completed_from_i_s_r.html", null ],
    [ "xMessageBufferReceiveCompletedFromISR", "group__x_message_buffer_receive_completed_from_i_s_r.html", null ],
    [ "xQueueCreate", "group__x_queue_create.html", null ],
    [ "xQueueCreateStatic", "group__x_queue_create_static.html", null ],
    [ "xQueueSend", "group__x_queue_send.html", null ],
    [ "xQueueOverwrite", "group__x_queue_overwrite.html", null ],
    [ "xQueuePeek", "group__x_queue_peek.html", null ],
    [ "xQueuePeekFromISR", "group__x_queue_peek_from_i_s_r.html", null ],
    [ "xQueueReceive", "group__x_queue_receive.html", null ],
    [ "uxQueueMessagesWaiting", "group__ux_queue_messages_waiting.html", null ],
    [ "vQueueDelete", "group__v_queue_delete.html", null ],
    [ "xQueueSendFromISR", "group__x_queue_send_from_i_s_r.html", null ],
    [ "xQueueOverwriteFromISR", "group__x_queue_overwrite_from_i_s_r.html", null ],
    [ "xQueueReceiveFromISR", "group__x_queue_receive_from_i_s_r.html", null ],
    [ "vSemaphoreCreateBinary", "group__v_semaphore_create_binary.html", null ],
    [ "xSemaphoreCreateBinary", "group__x_semaphore_create_binary.html", null ],
    [ "xSemaphoreCreateBinaryStatic", "group__x_semaphore_create_binary_static.html", null ],
    [ "xSemaphoreTake", "group__x_semaphore_take.html", null ],
    [ "xSemaphoreTakeRecursive", "group__x_semaphore_take_recursive.html", null ],
    [ "xSemaphoreGive", "group__x_semaphore_give.html", null ],
    [ "xSemaphoreGiveRecursive", "group__x_semaphore_give_recursive.html", null ],
    [ "xSemaphoreGiveFromISR", "group__x_semaphore_give_from_i_s_r.html", null ],
    [ "xSemaphoreCreateMutex", "group__x_semaphore_create_mutex.html", null ],
    [ "xSemaphoreCreateMutexStatic", "group__x_semaphore_create_mutex_static.html", null ],
    [ "xSemaphoreCreateRecursiveMutex", "group__x_semaphore_create_recursive_mutex.html", null ],
    [ "xSemaphoreCreateRecursiveMutexStatic", "group__x_semaphore_create_recursive_mutex_static.html", null ],
    [ "xSemaphoreCreateCounting", "group__x_semaphore_create_counting.html", null ],
    [ "xSemaphoreCreateCountingStatic", "group__x_semaphore_create_counting_static.html", null ],
    [ "vSemaphoreDelete", "group__v_semaphore_delete.html", null ],
    [ "xStreamBufferCreate", "group__x_stream_buffer_create.html", null ],
    [ "xStreamBufferCreateStatic", "group__x_stream_buffer_create_static.html", null ],
    [ "xStreamBufferSend", "group__x_stream_buffer_send.html", null ],
    [ "xStreamBufferSendFromISR", "group__x_stream_buffer_send_from_i_s_r.html", null ],
    [ "xStreamBufferReceive", "group__x_stream_buffer_receive.html", null ],
    [ "xStreamBufferReceiveFromISR", "group__x_stream_buffer_receive_from_i_s_r.html", null ],
    [ "vStreamBufferDelete", "group__v_stream_buffer_delete.html", null ],
    [ "xStreamBufferIsFull", "group__x_stream_buffer_is_full.html", null ],
    [ "xStreamBufferIsEmpty", "group__x_stream_buffer_is_empty.html", null ],
    [ "xStreamBufferReset", "group__x_stream_buffer_reset.html", null ],
    [ "xStreamBufferSpacesAvailable", "group__x_stream_buffer_spaces_available.html", null ],
    [ "xStreamBufferBytesAvailable", "group__x_stream_buffer_bytes_available.html", null ],
    [ "xStreamBufferSetTriggerLevel", "group__x_stream_buffer_set_trigger_level.html", null ],
    [ "xStreamBufferSendCompletedFromISR", "group__x_stream_buffer_send_completed_from_i_s_r.html", null ],
    [ "xStreamBufferReceiveCompletedFromISR", "group__x_stream_buffer_receive_completed_from_i_s_r.html", null ],
    [ "TaskHandle_t", "group___task_handle__t.html", null ],
    [ "taskYIELD", "group__task_y_i_e_l_d.html", null ],
    [ "taskENTER_CRITICAL", "group__task_e_n_t_e_r___c_r_i_t_i_c_a_l.html", null ],
    [ "taskEXIT_CRITICAL", "group__task_e_x_i_t___c_r_i_t_i_c_a_l.html", null ],
    [ "taskDISABLE_INTERRUPTS", "group__task_d_i_s_a_b_l_e___i_n_t_e_r_r_u_p_t_s.html", null ],
    [ "taskENABLE_INTERRUPTS", "group__task_e_n_a_b_l_e___i_n_t_e_r_r_u_p_t_s.html", null ],
    [ "xTaskCreate", "group__x_task_create.html", null ],
    [ "xTaskCreateStatic", "group__x_task_create_static.html", null ],
    [ "xTaskCreateRestricted", "group__x_task_create_restricted.html", null ],
    [ "xTaskCreateRestrictedStatic", "group__x_task_create_restricted_static.html", null ],
    [ "vTaskDelete", "group__v_task_delete.html", null ],
    [ "vTaskDelay", "group__v_task_delay.html", null ],
    [ "vTaskDelayUntil", "group__v_task_delay_until.html", null ],
    [ "xTaskAbortDelay", "group__x_task_abort_delay.html", null ],
    [ "uxTaskPriorityGet", "group__ux_task_priority_get.html", null ],
    [ "vTaskGetInfo", "group__v_task_get_info.html", null ],
    [ "vTaskPrioritySet", "group__v_task_priority_set.html", null ],
    [ "vTaskSuspend", "group__v_task_suspend.html", null ],
    [ "vTaskResume", "group__v_task_resume.html", null ],
    [ "vTaskResumeFromISR", "group__v_task_resume_from_i_s_r.html", null ],
    [ "vTaskStartScheduler", "group__v_task_start_scheduler.html", null ],
    [ "vTaskEndScheduler", "group__v_task_end_scheduler.html", null ],
    [ "vTaskSuspendAll", "group__v_task_suspend_all.html", null ],
    [ "xTaskResumeAll", "group__x_task_resume_all.html", null ],
    [ "xTaskGetTickCount", "group__x_task_get_tick_count.html", null ],
    [ "xTaskGetTickCountFromISR", "group__x_task_get_tick_count_from_i_s_r.html", null ],
    [ "uxTaskGetNumberOfTasks", "group__ux_task_get_number_of_tasks.html", null ],
    [ "pcTaskGetName", "group__pc_task_get_name.html", null ],
    [ "pcTaskGetHandle", "group__pc_task_get_handle.html", null ],
    [ "vTaskList", "group__v_task_list.html", null ],
    [ "vTaskGetRunTimeStats", "group__v_task_get_run_time_stats.html", null ],
    [ "ulTaskGetIdleRunTimeCounter", "group__ul_task_get_idle_run_time_counter.html", null ],
    [ "xTaskNotify", "group__x_task_notify.html", null ],
    [ "xTaskNotifyWait", "group__x_task_notify_wait.html", null ],
    [ "xTaskNotifyGive", "group__x_task_notify_give.html", null ],
    [ "ulTaskNotifyTake", "group__ul_task_notify_take.html", null ],
    [ "xTaskNotifyStateClear", "group__x_task_notify_state_clear.html", null ],
    [ "ulTaskNotifyValueClear", "group__ul_task_notify_value_clear.html", null ],
    [ "vTaskSetTimeOutState", "group__v_task_set_time_out_state.html", null ],
    [ "xTaskCheckForTimeOut", "group__x_task_check_for_time_out.html", null ],
    [ "CMSIS", "group___c_m_s_i_s.html", "group___c_m_s_i_s" ],
    [ "CMSIS_Device", "group___c_m_s_i_s___device.html", "group___c_m_s_i_s___device" ],
    [ "STM32H7xx_HAL_Driver", "group___s_t_m32_h7xx___h_a_l___driver.html", "group___s_t_m32_h7xx___h_a_l___driver" ]
];